### ISSUE TITLE
Don't die if a watched file is deleted

### ISSUE THREAD

**Issue by jtrussell** [jtrussell/buttle#14]
Kinda, annoying.

**Comment by jtrussell** [comment]
Note that this only seems to happen when the *containing folder* of a watched file is killed.

E.g.

```
buttle -w foo/bar.md

# separate process
rm -rf foo

# oh no! buttle crashed!
```

**Comment by jtrussell** [comment]
And here's what I get for a stack trace:

```
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: watch null EPERM
    at exports._errnoException (util.js:855:11)
    at FSEvent.FSWatcher._handle.onchange (fs.js:1296:21)
```

**Comment by jtrussell** [comment]
Seems relevant: https://github.com/nodejs/node-v0.x-archive/issues/4337
